[package]
name = "lktls-quic"
version = "0.2.1"
edition = "2021"

[dependencies]
lktls = { path = "../lktls" }
quinn-proto = { workspace = true }
quinn = { workspace = true, features = ["runtime-tokio", "ring", "rustls"] }
bytes = { workspace = true }
http = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
aws-lc-rs = { workspace = true }
aes = { workspace = true }
chacha20 = "0.9"
rustls-pki-types = { workspace = true }

[dev-dependencies]
lkh3 = { path = "../lkh3" }
h3 = { path = "../deps/h3/h3" }
h3-quinn = { path = "../deps/h3/h3-quinn" }
tokio = { workspace = true }
rcgen = "0.14"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
