//! Canonical (normalized) fingerprint representation for regression gating.
//!
//! This is the rich, comparison-oriented fingerprint type used by the
//! fingerprint-regression gate (see `docs/fingerprint-regression-design.md`).
//! It differs from a raw capture in one crucial way: **per-connection random
//! values are normalized while their positions are preserved.**
//!
//! Specifically, GREASE values (RFC 8701, `0x?A?A`) are randomized by the
//! client on every connection, but their *positions* are a stable, gate-worthy
//! part of the fingerprint (e.g. Chrome anchors the GREASE cipher at index 0).
//! So instead of stripping GREASE (which loses position) or keeping the random
//! value (which makes two captures of the same client mismatch), we **tokenize
//! GREASE in place**: keep the slot, replace the value with [`GREASE_TOKEN`].
//!
//! Extension *order* is intentionally preserved here as-emitted; the
//! shape-aware comparison step (which knows whether a profile shuffles
//! extensions) decides order-sensitivity — see the design doc §4.5.

use serde::{Deserialize, Serialize};

use lkprofile::{
    extract_alpn_protocols, extract_compress_cert_algorithms, extract_ec_point_formats,
    extract_key_share_curves, extract_record_size_limit, extract_signature_algorithms,
    extract_supported_groups, extract_supported_versions, is_grease_value, ParsedClientHello,
};

/// Canonical placeholder that every GREASE value is normalized to.
///
/// `0x0a0a` is itself a GREASE code-point (RFC 8701), so it can never collide
/// with a real cipher suite / group / extension type.
pub const GREASE_TOKEN: u16 = 0x0a0a;

/// Extensions that `lktls` auto-generates at runtime (their payload is implied
/// by other canonical fields), so their `source` is [`CanonicalExtSource::Auto`].
const WELL_KNOWN_EXTENSIONS: &[u16] = &[
    0x0000, 0x0005, 0x000a, 0x000b, 0x000d, 0x0010, 0x0012, 0x0015, 0x0016, 0x0017, 0x001b, 0x001c,
    0x0022, 0x0023, 0x0029, 0x002a, 0x002b, 0x002d, 0x0033, 0x0039, 0x4469, 0x44cd, 0xfe0d, 0xff01,
];
// Note: 0x0029 (pre_shared_key) and 0x002a (early_data) are well-known so their
// payloads are NOT captured as raw bytes — the PSK payload carries a binder and
// an obfuscated_ticket_age that vary per connection (wall-clock dependent), so
// only the extension's presence and (anchored-last) position are fingerprinted.

/// Tokenize a single value: GREASE → [`GREASE_TOKEN`], everything else unchanged.
#[inline]
pub fn tokenize(value: u16) -> u16 {
    if is_grease_value(value) {
        GREASE_TOKEN
    } else {
        value
    }
}

/// Tokenize every GREASE value in a list **in place** (positions preserved).
fn tokenize_vec(mut values: Vec<u16>) -> Vec<u16> {
    for v in &mut values {
        *v = tokenize(*v);
    }
    values
}

/// Where a canonical extension's payload comes from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CanonicalExtSource {
    /// Auto-generated by `lktls` (payload implied by other canonical fields).
    Auto,
    /// A GREASE extension (random value normalized to [`GREASE_TOKEN`]).
    Grease,
    /// An unknown extension carried as raw bytes (hex-encoded; part of the
    /// fingerprint). A struct variant (not a tuple) so it serializes cleanly
    /// under the internally-tagged representation.
    Raw { data: String },
}

/// A single canonical extension: its (possibly tokenized) type plus source.
/// Order within [`CanonicalTlsFingerprint::extensions`] is meaningful.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CanonicalExtension {
    /// Extension type code-point (GREASE tokenized to [`GREASE_TOKEN`]).
    pub extension_type: u16,
    /// Where the payload comes from.
    pub source: CanonicalExtSource,
}

/// Canonical TLS ClientHello fingerprint with GREASE normalized in place.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CanonicalTlsFingerprint {
    /// `legacy_version` from the ClientHello header (typically `0x0303`).
    pub legacy_version: u16,
    /// Cipher suites in wire order; GREASE tokenized in place.
    pub cipher_suites: Vec<u16>,
    /// Extensions in wire order (GREASE tokenized; order significant).
    pub extensions: Vec<CanonicalExtension>,
    /// `supported_groups` (0x000a) in order; GREASE tokenized.
    pub supported_groups: Vec<u16>,
    /// `signature_algorithms` (0x000d) in order.
    pub signature_algorithms: Vec<u16>,
    /// `ec_point_formats` (0x000b).
    pub ec_point_formats: Vec<u8>,
    /// Compression methods (typically `[0x00]`).
    pub compression_methods: Vec<u8>,
    /// `supported_versions` (0x002b) in order; GREASE tokenized.
    pub supported_versions: Vec<u16>,
    /// `key_share` (0x0033) curve code-points in order; GREASE tokenized.
    pub key_share_curves: Vec<u16>,
    /// ALPN protocols (0x0010).
    pub alpn_protocols: Vec<String>,
    /// ALPS protocols (0x4469 / 0x44cd), if present.
    pub alps_protocols: Option<Vec<String>>,
    /// `compress_certificate` (0x001b) algorithms, if present.
    pub compress_cert_algorithms: Option<Vec<u16>>,
    /// `record_size_limit` (0x001c), if present.
    pub record_size_limit: Option<u16>,
    /// Length of the session ID field (the value itself is random — excluded).
    pub session_id_length: u8,
    /// Whether the `padding` extension (0x0015) is present.
    pub has_padding: bool,
    /// Whether the `encrypted_client_hello` extension (0xfe0d) is present.
    pub has_ech: bool,
}

impl CanonicalTlsFingerprint {
    /// Build a canonical fingerprint from a parsed ClientHello, tokenizing every
    /// GREASE value in place (positions preserved).
    pub fn from_parsed(ch: &ParsedClientHello) -> Self {
        let mut supported_groups = Vec::new();
        let mut signature_algorithms = Vec::new();
        let mut ec_point_formats = Vec::new();
        let mut supported_versions = Vec::new();
        let mut key_share_curves = Vec::new();
        let mut alpn_protocols = Vec::new();
        let mut alps_protocols = None;
        let mut compress_cert_algorithms = None;
        let mut record_size_limit = None;
        let mut has_padding = false;
        let mut has_ech = false;

        for ext in &ch.extensions {
            if is_grease_value(ext.extension_type) {
                continue;
            }
            match ext.extension_type {
                0x000a => supported_groups = tokenize_vec(extract_supported_groups(&ext.data)),
                0x000b => ec_point_formats = extract_ec_point_formats(&ext.data),
                0x000d => signature_algorithms = extract_signature_algorithms(&ext.data),
                0x0010 => alpn_protocols = extract_alpn_protocols(&ext.data),
                0x0015 => has_padding = true,
                0x001b => {
                    compress_cert_algorithms = Some(extract_compress_cert_algorithms(&ext.data))
                }
                0x001c => record_size_limit = extract_record_size_limit(&ext.data),
                0x002b => supported_versions = tokenize_vec(extract_supported_versions(&ext.data)),
                0x0033 => key_share_curves = tokenize_vec(extract_key_share_curves(&ext.data)),
                0x4469 | 0x44cd => alps_protocols = Some(extract_alpn_protocols(&ext.data)),
                0xfe0d => has_ech = true,
                _ => {}
            }
        }

        let extensions = ch
            .extensions
            .iter()
            .map(|e| {
                if is_grease_value(e.extension_type) {
                    CanonicalExtension {
                        extension_type: GREASE_TOKEN,
                        source: CanonicalExtSource::Grease,
                    }
                } else if WELL_KNOWN_EXTENSIONS.contains(&e.extension_type) || e.data.is_empty() {
                    CanonicalExtension {
                        extension_type: e.extension_type,
                        source: CanonicalExtSource::Auto,
                    }
                } else {
                    CanonicalExtension {
                        extension_type: e.extension_type,
                        source: CanonicalExtSource::Raw {
                            data: hex::encode(&e.data),
                        },
                    }
                }
            })
            .collect();

        Self {
            legacy_version: ch.protocol_version,
            cipher_suites: tokenize_vec(ch.cipher_suites.clone()),
            extensions,
            supported_groups,
            signature_algorithms,
            ec_point_formats,
            compression_methods: ch.compression_methods.clone(),
            supported_versions,
            key_share_curves,
            alpn_protocols,
            alps_protocols,
            compress_cert_algorithms,
            record_size_limit,
            session_id_length: ch.session_id_length,
            has_padding,
            has_ech,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lkprofile::ParsedExtension;

    fn ext(extension_type: u16, data: Vec<u8>) -> ParsedExtension {
        ParsedExtension {
            extension_type,
            data,
        }
    }

    /// A ClientHello with a GREASE cipher at index 0 and a GREASE extension
    /// bookend, mirroring Chrome's layout.
    fn ch_with_grease() -> ParsedClientHello {
        ParsedClientHello {
            protocol_version: 0x0303,
            session_id_length: 32,
            // GREASE cipher anchored first, then two real ciphers.
            cipher_suites: vec![0x3a3a, 0x1301, 0x1302],
            compression_methods: vec![0x00],
            extensions: vec![
                ext(0xbaba, vec![]),     // GREASE extension bookend
                ext(0x0000, vec![1, 2]), // SNI (well-known)
                // supported_groups with a GREASE group first
                ext(0x000a, encode_u16_list(&[0xcaca, 0x001d, 0x0017])),
                ext(0xdead, vec![9, 9]), // unknown extension with data
            ],
        }
    }

    /// Encode a u16 list as a supported_groups payload: u16 list-length + items.
    fn encode_u16_list(items: &[u16]) -> Vec<u8> {
        let mut out = Vec::new();
        let byte_len = (items.len() * 2) as u16;
        out.extend_from_slice(&byte_len.to_be_bytes());
        for it in items {
            out.extend_from_slice(&it.to_be_bytes());
        }
        out
    }

    #[test]
    fn grease_cipher_is_tokenized_in_place_not_stripped() {
        let fp = CanonicalTlsFingerprint::from_parsed(&ch_with_grease());
        // Position preserved (length unchanged), value normalized to the token.
        assert_eq!(fp.cipher_suites, vec![GREASE_TOKEN, 0x1301, 0x1302]);
    }

    #[test]
    fn grease_extension_value_is_tokenized_and_position_preserved() {
        let fp = CanonicalTlsFingerprint::from_parsed(&ch_with_grease());
        // First extension is the GREASE bookend → token + Grease source, at index 0.
        assert_eq!(fp.extensions[0].extension_type, GREASE_TOKEN);
        assert_eq!(fp.extensions[0].source, CanonicalExtSource::Grease);
        // Order preserved: SNI second.
        assert_eq!(fp.extensions[1].extension_type, 0x0000);
        assert_eq!(fp.extensions[1].source, CanonicalExtSource::Auto);
        // Unknown extension with data → Raw (hex-encoded).
        assert_eq!(fp.extensions[3].extension_type, 0xdead);
        assert_eq!(
            fp.extensions[3].source,
            CanonicalExtSource::Raw {
                data: "0909".to_string()
            }
        );
    }

    #[test]
    fn grease_in_supported_groups_is_tokenized_in_place() {
        let fp = CanonicalTlsFingerprint::from_parsed(&ch_with_grease());
        assert_eq!(fp.supported_groups, vec![GREASE_TOKEN, 0x001d, 0x0017]);
    }

    #[test]
    fn two_captures_with_different_grease_values_are_equal_after_canonicalization() {
        let mut a = ch_with_grease();
        let mut b = ch_with_grease();
        // Different random GREASE values at the same positions.
        a.cipher_suites[0] = 0x1a1a;
        b.cipher_suites[0] = 0xfafa;
        a.extensions[0] = ext(0x2a2a, vec![]);
        b.extensions[0] = ext(0xeaea, vec![]);
        assert_eq!(
            CanonicalTlsFingerprint::from_parsed(&a),
            CanonicalTlsFingerprint::from_parsed(&b),
            "canonical fingerprints must match once GREASE is tokenized"
        );
    }

    #[test]
    fn token_is_itself_a_grease_value_so_never_collides() {
        assert!(is_grease_value(GREASE_TOKEN));
    }
}
